name: reddit_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter_riverpod: ^2.1.1
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  fpdart: ^0.3.0
  routemaster: ^1.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.2
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  any_link_preview: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: ZenDots
      fonts:
        - asset: fonts/ZenDots-Regular.ttf
          weight: 700

