// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCYvYpMJcoFD4VbvY1nZLrDPozV_p6kg',
    appId: '1:836553455765:web:0ae5482cb088dc4654039c',
    messagingSenderId: '836553455765',
    projectId: 'reedit-app',
    authDomain: 'reedit-app.firebaseapp.com',
    storageBucket: 'reedit-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfGL8ITnAnQufIPHZw1gSzBFvz8jr9Pg',
    appId: '1:836553455765:android:21c643dcb9e0d16154039c',
    messagingSenderId: '836553455765',
    projectId: 'reedit-app',
    storageBucket: 'reedit-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYq-9tw2fEjya3h-6xpPtAW-t9xI9Xhs',
    appId: '1:836553455765:ios:851766b672b0d87654039c',
    messagingSenderId: '836553455765',
    projectId: 'reedit-app',
    storageBucket: 'reedit-app.appspot.com',
    iosClientId: '836553455765-redg0jdaociji3358tmgrvt5t411hdmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
